### ISSUE TITLE
Window Binary

### ISSUE THREAD

**Issue by t0m5k1** [dekstop/vcvrackplugins_dekstop#11]
Is there any possibility we can have a windows binary release for 0.5.0 ?

**Comment by phdsg** [comment]
[dekstop-dev_f4526cb-win.zip](https://github.com/dekstop/vcvrackplugins_dekstop/files/1503016/dekstop-dev_f4526cb-win.zip)

**Comment by t0m5k1** [comment]
wow thank you :)
Was not expecting a response that fast!

**Comment by dekstop** [comment]
Thanks! Will add both Linux/Win binaries to the 0.5.0 release.
