### ISSUE TITLE
Please release the windows version .dll

### ISSUE THREAD

**Issue by synthi** [dekstop/vcvrackplugins_dekstop#2]

**Comment by dekstop** [comment]
Unfortunately I don't have a Windows machine! Maybe someone else can compile it and share a zip?

**Comment by synthi** [comment]
I hope someone can chime in. Eager to try your modules!
ps. Can´t OSX load a win7 machine in a virtual desktop or something. I`m not into mac but remember a friend was programming all the OS versions 8OSX, WIN Linux) inside his OSX machine

**Comment by antoniograzioli** [comment]
I can compile for you on win/mac/linux if you wish.

**Comment by dekstop** [comment]
@antoniograzioli that would be great, many thanks! Probably best to only compile the 0.3.2 source for now, linked/tagged here:
https://github.com/dekstop/vcvrackplugins_dekstop/releases/tag/0.3.2

I've made some changes towards the upcoming 0.4 API already, but expect it'll be a moving target for now.

**Comment by antoniograzioli** [comment]
I can try this afternoon, time permitting . Do you need Linux as well ?

(BTW I am also updating all my plugins for v. 0.4 and removing all those getf and setf as well as adding .value and .active here and there ;-)

**Comment by dekstop** [comment]
There's no rush at all, anything you can easily produce will be appreciated :) 

Also bear in mind that as soon as 0.4 is released, the 0.3.2 build won't be downloaded much. So I'd be equally happy to wait for the 0.4 release, if you're short on time.

**Comment by antoniograzioli** [comment]
well it should just be a matter of 1) open my laptop 2) git clone your repo 3) make it 4) zip it and upload.
I am on my Mac now and the Win10 Laptop is in another room, just too lazy now ;-)

**Comment by antoniograzioli** [comment]
HI Martin, 
here it is:

http://www.autodafe.net/tmp/vcvrackplugins_dekstop.zip

(quick ZIP of all files in the folder including the .dll file). I tested it under v.032 and they load correctly, I haven't tested carefully though.
Let me know when you have downloaded it and I'll delete it.

**Comment by dekstop** [comment]
Thanks Antonio, you're a star! I uploaded a .zip for the Windows release here:
https://github.com/dekstop/vcvrackplugins_dekstop/releases/tag/0.3.2

**Comment by antoniograzioli** [comment]
thumbs up, I am glad if I can be of help...and thank you too for your contribution to VCV rack

**Comment by antoniograzioli** [comment]
Isee that you miss Linux, I can build it to...not tonight, there's the new Star Trek Episode to watch ;-)
