### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by Strum** [dekstop/vcvrackplugins_dekstop#3]
Tried clone the repository and building, fails at first file.

Windows 7 Pro 64

Development version of Rack.

src/Recorder.cpp: In constructor 'Recorder::Recorder()':
src/Recorder.cpp:34:57: error: no matching function for call to 'rack::Module::Module(Recorder::ParamIds, Recorder::InputIds, Recorder::OutputIds)'
  Recorder() : Module(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS) {}
                                                         ^
In file included from ../../include/rack.hpp:6:0,
                 from src/dekstop.hpp:1,
                 from src/Recorder.cpp:3:
../../include/engine.hpp:10:8: note: candidate: rack::Module::Module()
 struct Module {
        ^~~~~~
../../include/engine.hpp:10:8: note:   candidate expects 0 arguments, 3 provided
../../include/engine.hpp:10:8: note: candidate: rack::Module::Module(const rack::Module&)
../../include/engine.hpp:10:8: note:   candidate expects 1 argument, 3 provided
src/Recorder.cpp: In member function 'virtual void Recorder::step()':
src/Recorder.cpp:149:45: error: request for member 'value' in '((Recorder*)this)->Recorder::<anonymous>.rack::Module::inputs.std::vector<float*>::operator[](((std::vector<float*>::size_type)(0 + i)))', which is of non-class type '__gnu_cxx::__alloc_traits<std::allocator<float*> >::value_type {aka float*}'
     f.samples[i] = inputs[AUDIO1_INPUT + i].value / 5.0;
                                             ^~~~~
make: *** [../../compile.mk:50: build/src/Recorder.cpp.o] Error 1

**Comment by dekstop** [comment]
The Rack API is currently undergoing changes, so plugins developed for 0.32 won't compile under 0.40. The current master is already tracking some of these changes, but I imagine there are more to come. In the meantime it's maybe best to checkout the 0.3.2 version of Rack, and the tagged changeset of the plugins here: https://github.com/dekstop/vcvrackplugins_dekstop/releases/tag/0.3.2

**Comment by Strum** [comment]
Ok that maybe the problem, I'm still using 0.3.1 dev code i think

I'm,new to git and contributing to open source projects so not really sure how to update the code or compile my own modules so they run in the release version.
