### ISSUE TITLE
Labels do not show for the current rack version

### ISSUE THREAD

**Issue by Euphorbium** [dekstop/vcvrackplugins_dekstop#6]
There are no labels displayed with the current dev version of rack. Recorder looks as intended, from the other two only clock multiplier is labeled, and no other markings on the modules.

**Comment by dekstop** [comment]
I finally updated the code for Rack 0.4.0, please check if it works now. Send me a screenshot if it's still an issue: https://github.com/dekstop/vcvrackplugins_dekstop/releases

**Comment by nay-seven** [comment]
For info, same issues here:
rack0.4.0
Mac Yosemite

![desktop modules](https://user-images.githubusercontent.com/13808201/32668379-ac5de0dc-c63d-11e7-90ad-8dbbaed08d10.png)

**Comment by dekstop** [comment]
Ah ok, thanks. It looks like it's an issue with background texture loading. Unfortunately this part of VCV will change a lot over the coming versions... I'm just looking at converting backgrounds to SVGs.

**Comment by dekstop** [comment]
I just pushed an SVG version of the plugins. I you can compile it yourself, then please check if current HEAD improves things. It compiles against the most recent Rack development version.

**Comment by nay-seven** [comment]
Thanks , but no compilation possible here ;-)

**Comment by dekstop** [comment]
Here's an OSX build: [dekstop-osx-20171110a.zip](https://github.com/dekstop/vcvrackplugins_dekstop/files/1462408/dekstop-osx-20171110a.zip)

**Comment by nay-seven** [comment]
don't work, nothing appear in Rack ( i've rename the folder dekstop-osx) 
and there's only 2 svg files in the res folder  ?

**Comment by dekstop** [comment]
Hm ok, then I don't know -- maybe we need to wait until things settle for the 0.5.0 release. (Only two of the plugins use a texture. The Recorder plugin doesn't.)

**Comment by nay-seven** [comment]
yes, of course, better to wait 0.5, will be soon now ( #ihope) ;-)

**Comment by dekstop** [comment]
v0.5.0 was just released! When you have a moment, please update both your VCV and the dekstop plugin, and try again: 

https://github.com/VCVRack/Rack/releases
https://github.com/dekstop/vcvrackplugins_dekstop/releases

**Comment by nay-seven** [comment]
Works fine ! Thanks a lot

**Comment by dekstop** [comment]
Hah, magic!
