### ISSUE TITLE
v 0.4 compatibility ?

### ISSUE THREAD

**Issue by odahan** [dekstop/vcvrackplugins_dekstop#7]
do you plan a new release for vcv rack 0.4 ?
Your recorder is really so helpful !
thanks in advance

**Comment by dekstop** [comment]
Hallo! Yes, I intend to migrate to 0.4; unfortunately work and life are keeping me busy... I'm not sure yet when I'll find the time for this, but I'm definitely keen to do it.

**Comment by ortenheim** [comment]
When building for 0.40 i get this error:

`Oceanhubs-iMac:vcvrackplugins_dekstop ohimacmikael$ git submodule update --init --recursive
Oceanhubs-iMac:vcvrackplugins_dekstop ohimacmikael$ make -B all
c++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -DVERSION_dev -MMD -O3 -march=nocona -ffast-math -Wall -g -DARCH_MAC -mmacosx-version-min=10.7 -Iportaudio -std=c++11 -stdlib=libc++ -c -o build/src/GateSeq8.cpp.o src/GateSeq8.cpp
src/GateSeq8.cpp:30:2: error: unknown type name 'SchmittTrigger'
        SchmittTrigger clockTrigger; // for external clock
        ^
src/GateSeq8.cpp:31:2: error: unknown type name 'SchmittTrigger'
        SchmittTrigger runningTrigger;
        ^
src/GateSeq8.cpp:32:2: error: unknown type name 'SchmittTrigger'
        SchmittTrigger resetTrigger;
        ^
src/GateSeq8.cpp:36:2: error: unknown type name 'SchmittTrigger'
        SchmittTrigger gateTriggers[NUM_GATES];
        ^
src/GateSeq8.cpp:201:12: error: cannot initialize a parameter of type 'rack::Module *' with an
      lvalue of type 'GateSEQ8 *'
        setModule(module);
                  ^~~~~~
../../include/app.hpp:37:25: note: passing argument to parameter 'module' here
        void setModule(Module *module);
                               ^
src/GateSeq8.cpp:216:11: error: no matching function for call to 'createParam'
        addParam(createParam<Davies1900hSmallBlackKnob>(Vec(17, 56), module, GateSEQ8::...
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:41:14: note: candidate function [with TParam =
      rack::Davies1900hSmallBlackKnob] not viable: no known conversion from 'GateSEQ8 *' to
      'rack::Module *' for 2nd argument
ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float ma...
             ^
src/GateSeq8.cpp:217:11: error: no matching function for call to 'createParam'
        addParam(createParam<LEDButton>(Vec(60, 61-1), module, GateSEQ8::RUN_PARAM, 0.0...
                 ^~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:41:14: note: candidate function [with TParam = rack::LEDButton] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float ma...
             ^
src/GateSeq8.cpp:219:11: error: no matching function for call to 'createParam'
        addParam(createParam<LEDButton>(Vec(98, 61-1), module, GateSEQ8::RESET_PARAM, 0...
                 ^~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:41:14: note: candidate function [with TParam = rack::LEDButton] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float ma...
             ^
src/GateSeq8.cpp:221:11: error: no matching function for call to 'createParam'
        addParam(createParam<Davies1900hSmallBlackSnapKnob>(Vec(132, 56), module, GateS...
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:41:14: note: candidate function [with TParam =
      rack::Davies1900hSmallBlackSnapKnob] not viable: no known conversion from 'GateSEQ8 *' to
      'rack::Module *' for 2nd argument
ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float ma...
             ^
src/GateSeq8.cpp:224:11: error: no matching function for call to 'createInput'
        addInput(createInput<PJ301MPort>(Vec(portX[0]-1, 99-1), module, GateSEQ8::CLOCK...
                 ^~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:52:7: note: candidate function [with TPort = rack::PJ301MPort] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
Port *createInput(Vec pos, Module *module, int inputId) {
      ^
src/GateSeq8.cpp:225:11: error: no matching function for call to 'createInput'
        addInput(createInput<PJ301MPort>(Vec(portX[1]-1, 99-1), module, GateSEQ8::EXT_C...
                 ^~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:52:7: note: candidate function [with TPort = rack::PJ301MPort] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
Port *createInput(Vec pos, Module *module, int inputId) {
      ^
src/GateSeq8.cpp:226:11: error: no matching function for call to 'createInput'
        addInput(createInput<PJ301MPort>(Vec(portX[2]-1, 99-1), module, GateSEQ8::RESET...
                 ^~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:52:7: note: candidate function [with TPort = rack::PJ301MPort] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
Port *createInput(Vec pos, Module *module, int inputId) {
      ^
src/GateSeq8.cpp:227:11: error: no matching function for call to 'createInput'
        addInput(createInput<PJ301MPort>(Vec(portX[3]-1, 99-1), module, GateSEQ8::STEPS...
                 ^~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:52:7: note: candidate function [with TPort = rack::PJ301MPort] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
Port *createInput(Vec pos, Module *module, int inputId) {
      ^
src/GateSeq8.cpp:245:13: error: no matching function for call to 'createParam'
                        addParam(createParam<LEDButton>(Vec(22 + x*25, 155+y*25+3), mod...
                                 ^~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:41:14: note: candidate function [with TParam = rack::LEDButton] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float ma...
             ^
src/GateSeq8.cpp:248:13: error: no matching function for call to 'createOutput'
                addOutput(createOutput<PJ301MPort>(Vec(320, 155+y*25), module, GateSEQ8...
                          ^~~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:62:7: note: candidate function [with TPort = rack::PJ301MPort] not
      viable: no known conversion from 'GateSEQ8 *' to 'rack::Module *' for 2nd argument
Port *createOutput(Vec pos, Module *module, int outputId) {
      ^
15 errors generated.
make: *** [build/src/GateSeq8.cpp.o] Error 1
Oceanhubs-iMac:vcvrackplugins_dekstop ohimacmikael$`

**Comment by ortenheim** [comment]
downloaded binary for mac: 0.4.0

when folder name is plugins/dekstop:
Failed to load library ./plugins/dekstop/plugin.dylib: dlopen(./plugins/dekstop/plugin.dylib, 2): Symbol not found: __ZN4rack8MenuItem12onMouseLeaveEv
  Referenced from: ./plugins/dekstop/plugin.dylib
  Expected in: flat namespace
 in ./plugins/dekstop/plugin.dylib

what am I doing wrong here?

**Comment by dekstop** [comment]
Thanks for all your patience... it's been a busy month. There's now a new release for Rack v0.4.0, please see if this one works for you. (Only the OSX version is precompiled as I don't have access to a Windows or Linux machine.) https://github.com/dekstop/vcvrackplugins_dekstop/releases
